### ISSUE TITLE
add-by-geotagged venues not setting wof/iso:country

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#296] opened 2017-07-12 12:26 UTC
I noticed that there were a bunch of bunk SG venues badly geocoded in to Taiwan:

https://whosonfirst.mapzen.com/spelunker/id/85632403/descendants/?exclude=nullisland&placetype=venue

So I am in the process of cleaning them up and noticed that the recent add-by-geotagged venues in Taiwan are missing both `wof:country` and `iso:country` properties. For example:

```
...
1108397917 Lejerbo Vuggestue (DK, DK)
1108409201 Svane Electronic ApS (DK, DK)
1108472587 Bilcentret A/S (DK, DK)
1108472883 Due A/S, Gunner (DK, DK)
1108476543 Dansk Auto Hi-Fi A/S (DK, DK)
1141959903 Black Bear Coffee (, )
1141959905 Minder Vegetarian (, )
1141959907 Xiangshan Trail (, )
1141959909 Taipei 101 (, )
```

**Comment by dphiffer** [comment] 2017-07-13 09:53
Hmm that's very odd. I'm gonna fix those and then track down what the cause might be.

**Comment by dphiffer** [comment] 2017-07-13 15:00
I figured it out. Should be fixed now!

**Closed as completed by dphiffer** 2017-07-13 15:00 UTC
Labels: bug, geotagged
